# Generated by Django 4.2.14 on 2024-07-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDiskIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstkeywordcode', models.CharField(max_length=255)),
                ('firstkeywordrange', models.CharField(max_length=255)),
                ('secondkeywordcode', models.CharField(max_length=255)),
                ('secondkeywordrange', models.CharField(max_length=255)),
                ('thirdkeywordcode', models.CharField(max_length=255)),
                ('thirdkeywordrange', models.CharField(max_length=255)),
                ('foutrhkeywordcode', models.CharField(max_length=255)),
                ('fourthkeywordrange', models.CharField(max_length=255)),
                ('fifthkeywordcode', models.CharField(max_length=255)),
                ('fifthkeywordrange', models.CharField(max_length=255)),
                ('gatherflag', models.CharField(max_length=255)),
                ('tracetype', models.CharField(max_length=255)),
                ('userange', models.CharField(max_length=255)),
                ('timewindowinput', models.CharField(max_length=255)),
                ('headerword', models.CharField(max_length=255)),
                ('headerrange', models.CharField(max_length=255)),
                ('rangeword', models.CharField(max_length=255)),
                ('randomrange', models.CharField(max_length=255)),
                ('gatherinput', models.CharField(max_length=255)),
                ('recreate', models.CharField(max_length=255)),
                ('headeronly', models.CharField(max_length=255)),
                ('sortsequence', models.CharField(max_length=255)),
                ('consistencycheck', models.CharField(max_length=255)),
            ],
        ),
    ]
